version: "3"
services:
  spring_dockerizing:
    image: spring_dockerizing
    ports:
      - "8081:8080"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - employee-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_dockerizing

networks:
  employee-mysql: